newrelic:
  policy: MCP Order Intake
  refreshrate: 10000

gitlab:
  groupIds: 
    - 107
    - 105
    - 338
    - 388
  refreshRate: 300000

slideshow:
  youtube:
    - ddFvjfvPnqk #earth
    - qrgX5W1NiGQ #puffins
    #- 1tyxTfhlDmk #fish
    - p5mu_febWXg #bears
    - uYSyrvvoWlY #giraffes
  twitch:
    # - starcraft
  rate: 120000
